name: Windows-MSVC
# on: [push]
on: 
  push:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/build_windows_msvc.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/build_windows_msvc.yml' 
jobs:
  build:
    name: Build
    ## 運行的作業系統
    runs-on: ${{ matrix.os }}
    strategy:
      ## 矩陣配置
      matrix:
        app_name: [QtGithubActionDemo]
        os: [windows-2019]
        # 5.9.9 :   msvc2015
        # 5.10.1 :  msvc2015
        # 5.11.3 :  msvc2015
        # 5.12.10 : msvc2017
        # 5.13.2 :  msvc2017
        # 5.14.2 :  msvc2017
        # 5.15.2 :  msvc2019
        # 6.0.0 :   msvc2019
        qt_ver: [5.15.2]
        ##  win64_msvc, win32_msvc 
        qt_target: [win32_msvc,win64_msvc]
        qt_arch: [msvc]
        msvc_version: [2019/Enterprise]
    env:
        app_name: ${{ matrix.app_name }}
        msvc_version: ${{ matrix.msvc_version }}
        qt_ver: ${{ matrix.qt_ver }}
        qt_target: ${{ matrix.qt_target }}
        qt_arch: ${{ matrix.qt_arch }}
        ## 搭配使用的模組，請用空格隔開
        qt_modules: qtbase qtquickcontrols2 qtquickcontrols qtdeclarative qttools
        archive_name: ${{ matrix.app_name }}_${{ matrix.qt_target }}_Qt${{matrix.qt_ver}}
    ## 步驟
    steps:
      ## 切換至目前提交
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: 'true'
      ## 配置 python 環境
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      ## 安裝相依的套件
      # - name:  install library
      #   run: |

      ## 下載 Qt 編譯環境 
      - name: Install Qt
        run: |
          python ./util/ci/get_qt.py
      ## 建置
      - name: build source code
        run: |
          python ./util/ci/build.py
      ## 打包
      - name: Package
        run: |
          python ./util/ci/deploy.py
      ## 上傳至 github artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.archive_name }}
          path: ${{ env.archive_name }}.zip
      ## 上傳至 github Release 項目 （有上git tag 的commit）
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.archive_name }}.zip
          asset_name: ${{ env.archive_name }}.zip
          tag: ${{ github.ref }}
          overwrite: true