name: Android
# on: [push] 
on: 
  push:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/build_android.yml'
  pull_request:
    paths:
      - '*.pro'
      - 'src/**'
      - '.github/workflows/build_android.yml'  
# ref:
# https://doc.qt.io/qt-5/deployment-android.html#building-the-android-application 
# https://www.kdab.com/qt-for-android-better-than-ever-before/
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        app_name: [QtGithubActionDemo]
        os: [ubuntu-20.04]
        qt_ver: [5.15.2]
        # android
        qt_target: [android]
        # use ANDROID_ABIS variable to Specifies a list of Android target ABIs. e.g.: armeabi-v7a, arm64-v8a, x86, x86_64
        # https://doc.qt.io/qt-5/qmake-variable-reference.html#android-abi
        qt_arch: [x86,armeabi-v7a]
    env:
        app_name: ${{ matrix.app_name }}
        qt_ver: ${{ matrix.qt_ver }}
        qt_target: ${{ matrix.qt_target }}
        qt_arch: ${{ matrix.qt_arch }}
        # 搭配使用的模組，請用空格隔開
        qt_modules: qtbase qtquickcontrols2 qtquickcontrols qtdeclarative
        archive_name: ${{ matrix.app_name }}_${{ matrix.qt_target }}_Qt${{matrix.qt_ver}}
    steps:

      ## 切換至目前提交
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: 'true'
      ## 配置 python 環境
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      ## 下載 Qt 編譯環境 
      - name: Install Qt
        run: python ./util/ci/get_qt.py
      ## 建置
      - name: Build source code
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          python ./util/ci/build.py
      ## 打包
      - name: Package
        run: |
          python ./util/ci/deploy.py
      ## 上傳至 github artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.archive_name }}.zip
          path: build/android-build/${{ env.app_name }}.apk
      ## 上傳至 github Release 項目 （有上git tag 的commit）
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/android-build/${{ env.app_name }}.apk
          asset_name: ${{ env.archive_name }}.apk
          tag: ${{ github.ref }}
          overwrite: true